export const projects = [
  {
    title: "TradingOS",
    type: "Autonomous trading system",
    image: "/img/tradingos.jpg",
    href: "https://trading-os-sable.vercel.app",
    color: "#22c55e",
    index: "01",
  },
  {
    title: "Finance OS",
    type: "Personal finance platform",
    image: "/img/financeos.jpg",
    href: "https://kadambamoodbidri.in",
    color: "#a855f7",
    index: "02",
  },
  {
    title: "Chatu",
    type: "Voice-first social",
    image: "/img/chatu.jpg",
    href: "https://chatu.in",
    color: "#c2610c",
    index: "03",
  },
  {
    title: "Kateel Construction",
    type: "Site management platform",
    image: "/img/kateel.jpg",
    href: "https://kateel.in",
    color: "#2563eb",
    index: "04",
  },
  {
    title: "Adhishtam Digital",
    type: "Agency website",
    image: "/img/adhishtam.jpg",
    href: "https://adhishtam.com",
    color: "#2f9e6e",
    index: "05",
  },
  {
    title: "Shobha Digital Studio",
    type: "Photography studio",
    image: "/img/shobhadigital.jpg",
    href: "https://shobhadigitalstudio.in",
    color: "#c9a227",
    index: "06",
  },
  {
    title: "Belvai Temple",
    type: "Heritage temple site",
    image: "/img/belvaitemple.jpg",
    href: "https://belvaitemple.in",
    color: "#d97706",
    index: "07",
  },
  {
    title: "Shivam Digital",
    type: "Photography experience",
    image: "/img/img_1.jpg",
    href: "https://shivamdigital.vercel.app",
    color: "#8b5cf6",
    index: "08",
  },
  {
    title: "Divas Event Planners",
    type: "Event platform",
    image: "/img/divas.jpg",
    href: "https://divaseventplanners.vercel.app",
    color: "#ec4899",
    index: "09",
  },
  {
    title: "G3 Builders",
    type: "Architecture showcase",
    image: "/img/projectsByG3.jpg",
    href: "https://projectsbyg3.vercel.app",
    color: "#22d3ee",
    index: "10",
  },
  {
    title: "Comma Separator",
    type: "Developer utility",
    image: "/img/GPT.jpg",
    href: "https://commaseperatedvalues.vercel.app",
    color: "#a3e635",
    index: "11",
  },
  {
    title: "JSON Explorer",
    type: "Public API experiment",
    image: "/img/JSON.jpg",
    href: "https://testingjsondisplay.vercel.app",
    color: "#f59e0b",
    index: "12",
  },
  {
    title: "Resume in HTML",
    type: "Frontend study",
    image: "/img/resume.jpg",
    href: "https://resumehtmlcss-mauve.vercel.app",
    color: "#fb7185",
    index: "13",
  },
  {
    title: "Ocean Pearl",
    type: "Hospitality website",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1400&q=80",
    href: "https://oceanpearlujire.vercel.app",
    color: "#38bdf8",
    index: "14",
  },
];

export const skills = [
  "C#", ".NET Core", "Angular", "TypeScript", "React", "SQL Server",
  "Microservices", "RabbitMQ", "GraphQL", "REST APIs", "AI / LLM", "Three.js",
];

export const experience = [
  {
    period: "2022 — NOW",
    role: "Software Engineer",
    company: "Cornerstone OnDemand · Pune",
    summary: "Building scalable product systems for performance goals, bulk data import, and AI-assisted workflows.",
    highlights: [
      "Led the Performance Goals migration from a monolith to message-driven microservices.",
      "Architected an Edge Import framework adopted across multiple teams.",
      "Took an AI goal-description generator from hackathon concept to production.",
      "Led security hardening, cross-team integrations, and developer mentorship.",
    ],
    stack: [".NET Core", "Angular", "RabbitMQ", "GraphQL", "SQL Server", "AI"],
  },
  {
    period: "2021 — 2022",
    role: "Associate Software Engineer",
    company: "Allstate · Bangalore",
    summary: "Shipped reliable features and analytics for a large-scale insurance agent platform.",
    highlights: [
      "Delivered core features for the My Claims module.",
      "Built and maintained REST services backed by Oracle.",
      "Partnered with QA and analytics teams to improve quality and product insight.",
    ],
    stack: ["C#", ".NET", "Oracle", "REST APIs", "Adobe Analytics"],
  },
];

export const education = [
  { year: "2021", title: "B.E. Computer Science", place: "MITE, Moodabidri", score: "8.2 CGPA" },
  { year: "2016", title: "Pre-University", place: "Jain Junior PU College", score: "87.67%" },
  { year: "2014", title: "SSLC", place: "Jain High School", score: "91.04%" },
];
